x-vy:
  anchors:
    IMAGE: stage:vscode_vydbg
    EXTENSION: vydir:vscode_vydbg

services:
  server:
    command: sleep 10000
    image: ${IMAGE}
    restart: unless-stopped
    user: user
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $EXTENSION:/myext

version: '3.6'
